name: CD

on:
  push:
    branches:
      - develop
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/develop'

    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig \
            --region ${{ vars.AWS_REGION }} \
            --name ${{ vars.EKS_CLUSTER_NAME }}

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Deploy Helm Chart
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)

          helm upgrade --install nginx \
            ./helm/app13 \
            --namespace dev \
            --create-namespace \
            -f helm/app13/values-dev.yaml \
            --set image.repository=$ACCOUNT_ID.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.ECR_REPOSITORY }} \
            --set image.tag=${{ github.sha }}

      - name: Verify Deployment
        run: |
          kubectl rollout status deployment/nginx -n dev --timeout=300s
          kubectl get pods -n dev
          kubectl get svc -n dev
          kubectl get ingress -n dev

  deploy-prod:
    if: github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig \
            --region ${{ vars.AWS_REGION }} \
            --name ${{ vars.EKS_CLUSTER_NAME }}

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Deploy Helm Chart
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)

          helm upgrade --install nginx \
            ./helm/app13 \
            --namespace prod \
            --create-namespace \
            -f helm/app13/values-prod.yaml \
            --set image.repository=$ACCOUNT_ID.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.ECR_REPOSITORY }} \
            --set image.tag=${{ github.sha }}

      - name: Verify Deployment
        run: |
          kubectl rollout status deployment/nginx -n prod --timeout=300s
          kubectl get pods -n prod
          kubectl get svc -n prod
          kubectl get ingress -n prod